# # See the configuration reference at https://symfony.com/bundles/SchebTwoFactorBundle/6.x/configuration.html
# scheb_two_factor:
#     security_tokens:
#         #- Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken
#         - Symfony\Component\Security\Http\Authenticator\Token\PostAuthenticationToken
#     google:
#         enabled: true



# config/packages/scheb_2fa.yaml
scheb_two_factor:
    security_tokens:
        #- Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken
        - Symfony\Component\Security\Http\Authenticator\Token\PostAuthenticationToken
        #- Acme\AuthenticationBundle\Token\CustomAuthenticationToken
    email:
        digits: 6
        enabled: true
        sender_email: ClassChecker@classchecker.com
        sender_name: Class Checker
        template: security/2fa_login.html.twig

